-- Crear roles
CREATE ROLE SuperDBA WITH LOGIN SUPERUSER CREATEDB CREATEROLE INHERIT REPLICATION BYPASSRLS;
CREATE ROLE readwrite;
CREATE ROLE readonly;

-- Asignar permisos a los roles
GRANT CONNECT ON DATABASE PryAdminAGL TO readwrite;
GRANT USAGE ON SCHEMA public TO readwrite;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO 
	readwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, 
	DELETE ON TABLES TO readwrite;

GRANT CONNECT ON DATABASE PryAdminAGL TO readonly;
GRANT USAGE ON SCHEMA public TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly;

SELECT datname from pg_database;